### PR TITLE
Updated to use ComputerCraft colours

### PR DESCRIPTION
**Pull request by theoriginalbit**
**Bugs found:**
- Colour palette block's default is not something picked from the palettes colour list, it is instead a static `#ff0000` this should be addressed
- Generating the Lua code places a hex string for example `"#ff0000"` instead of either `colours.red` or `16384`
- _[known]_ hovering over the colour the tooltip shows the rgb _[proposed fix]_ perhaps have another key in the array of colours that specifies tooltip?

### CODE REVIEW

**Comment by espertus** [comment]
On Thu, Nov 7, 2013 at 11:10 PM, Joshua Asbury notifications@github.comwrote:

> - Colour palette block's default is not something picked from list, it
>   is static #ff0000 this should be addressed
>   
>   This one's an easy fix.  You can specify this when creating the block.
>   Here's the definition from the original Blockly:

Blockly.Blocks['colour_picker'] = {
  // Colour picker.
  init: function() {
    this.setHelpUrl(Blockly.Msg.COLOUR_PICKER_HELPURL);
    this.setColour(20);
    this.appendDummyInput()
        .appendTitle(new Blockly.FieldColour('#ff0000'), 'COLOUR');
    this.setOutput(true, 'Colour');
    this.setTooltip(Blockly.Msg.COLOUR_PICKER_TOOLTIP);
  }
}

**Comment by espertus** [comment]
> - [known] hovering over the colour the tooltip shows the rgb _[proposed
>   fix]_ perhaps have another key in the array of colours that specifies
>   tooltip?
> 
> Unfortunately, this can't be fixed.  It's hardcoded into the widget.  I've
> wondered if this would be a deal breaker.

**Comment by espertus** [comment]
My previous reply was munged.  It should be: Unfortunately, this can't be fixed.  It's hardcoded into the widget.  I've
wondered if this would be a deal breaker.

**Comment by espertus** [comment]
On Thu, Nov 7, 2013 at 11:10 PM, Joshua Asbury notifications@github.comwrote:

> - Generating the Lua code places a hex string for example "#ff0000"instead of either
>   colours.red or 16384
> 
> Thanks for catching this.  I've fixed it.

FYI, I made the tooltip list the colour names.  I hope this will help make
up for the lack of useful hover text.

Ellen

**Comment by theoriginalbit** [comment]
> Here's the definition from the original Blockly:
> 
> Blockly.Blocks['colour_picker'] = {
>    // Colour picker.
>   init: function() {
>     this.setHelpUrl(Blockly.Msg.COLOUR_PICKER_HELPURL);
>     this.setColour(20);
>     this.appendDummyInput()
>         .appendTitle(new Blockly.FieldColour('#ff0000'), 'COLOUR');
>     this.setOutput(true, 'Colour');
>     this.setTooltip(Blockly.Msg.COLOUR_PICKER_TOOLTIP);
>   }
> }

Yeh ik, I read that, but I feel that `this.appendDummyInput().appendTitle(new BlocklyFieldColour('#ff0000'), 'COLOUR');` should actually display the colour of say the first element in the colour array, not only in this, but as an improvement in Blockly too, just incase someone does change the colour palette they don't then need to go and make another `colour_picker` like you've currently done for this.

> Unfortunately, this can't be fixed. It's hardcoded into the widget. I've wondered if this would be a deal breaker.

Widget? Its a coloured box........ Did you guys make the widget?

**Comment by espertus** [comment]
On Fri, Nov 8, 2013 at 6:27 PM, Joshua Asbury notifications@github.comwrote:

> Here's the definition from the original Blockly:
> 
> Blockly.Blocks['colour_picker'] = {
> // Colour picker.
> init: function() {
> this.setHelpUrl(Blockly.Msg.COLOUR_PICKER_HELPURL);
> this.setColour(20);
> this.appendDummyInput()
> .appendTitle(new Blockly.FieldColour('#ff0000'), 'COLOUR');
> this.setOutput(true, 'Colour');
> this.setTooltip(Blockly.Msg.COLOUR_PICKER_TOOLTIP);
> }
> }
> 
> Yeh ik, I read that, but I feel that this.appendDummyInput().appendTitle(new
> BlocklyFieldColour('#ff0000'), 'COLOUR'); should actually display the
> colour of say the first element in the colour array, not only in this, but
> as an improvement in Blockly too, just incase someone does change the
> colour palette they don't then need to go and make another colour_pickerlike you've currently done for this.

Fair enough.

>  Unfortunately, this can't be fixed. It's hardcoded into the widget. I've
> wondered if this would be a deal breaker.
> 
> Widget? Its a coloured box........ Did you guys make the widget?
> 
> No, we didn't make the widget (palette).  It may be part of Google's
> Closure library.  (I'm on the road now.)

Ellen

**Comment by theoriginalbit** [comment]
> Fair enough.

I'm glad that you now understand my reasoning behind what I was saying

> No, we didn't make the widget (palette). It may be part of Google's Closure library. (I'm on the road now.)

Oh ok. Fair enough then. Shame that it cannot be overrode :(

Have a safe trip to wherever you're headed.

**Pull request merged**
