### PR TITLE
Added ComputerCraft colours

### PR DESCRIPTION
**Pull request by theoriginalbit**
Still to add

[Colours Combine](http://computercraft.info/wiki/Colors.combine) _note:_ vararg function
[Colours Subtract](http://computercraft.info/wiki/Colors.subtract) _note:_ vararg function
[Colours Test](http://computercraft.info/wiki/Colors.test) _note:_ needs to accept this colour block as well as number blocks since a colour is just a number between 2^0 and 2^15

[Colours API](http://computercraft.info/wiki/Colors_%28API%29)

### CODE REVIEW

**Comment by espertus** [comment]
I implemented a [colour picker](http://test.blockly-lua.appspot.com/static/apps/code/index.html) but am not happy with it.  Specifically, I can't prevent it from display the RGB values on mouseover, but what we really want is the colour names, since someone might not be able to distinguish magenta, pink, and purple by sight (or RGB value).  Take a look and tell me what you think.

Other options are 16 distinct blocks or a dropdown menu.  An advantage of the former is that we can (I think) make each distinct block show up in its colour.  A disadvantage is that it causes a lot of blocks to be displayed, but it's not like the Colour\* category is over-populated or likely to be.

*Core Blockly uses "colour" because of Blockly's Canadian creator.  I thought I could switch to "color" now that I broke off on my own, but that would introduce conflict with both existing variable names and my new Australian colleague.  I guess I have to accept that the era of US hegemony is in the past.  :-)

**Comment by theoriginalbit** [comment]
Ok I'll take a look into it all, looks good though. I'm assuming that if I pull all the latest commits I'll get the colours palette.

I always type color when its variable names and/or text displayed to the user unless EN_UK or EN_AU is selected as the locale. The only times I use colour as names are
1. The original developer has, so I continue the style
2. In comments

**Comment by theoriginalbit** [comment]
Ok I just found all the hex values in the ComputerCraft mod and converted them from integers to hex... Here is the list

```
colors.white      HEX: #f0f0f0
colors.orange     HEX: #f2b233
colors.magenta    HEX: #e57fd8
colors.lightBlue  HEX: #99b2f2
colors.yellow     HEX: #dede6c
colors.lime       HEX: #7fcc19
colors.pink       HEX: #f2b2cc
colors.gray       HEX: #4c4c4c
colors.lightGray  HEX: #999999
colors.cyan       HEX: #4c99b2
colors.purple     HEX: #b266e5
colors.blue       HEX: #253192
colors.brown      HEX: #7f664c
colors.green      HEX: #57a64e
colors.red        HEX: #cc4c4c
colors.black      HEX: #191919
```

**Comment by espertus** [comment]
On Thu, Nov 7, 2013 at 7:59 PM, Joshua Asbury notifications@github.comwrote:

> Ok I just found all the hex values in the ComputerCraft mod and converted
> them from integers to hex...
> 
> Great!

You don't think it's too hard for people to eyeball colors from the
palette?  I guess we can always change it if people complain.

I didn't check in the code before but have now.  Of course, you'll have to
add the category and block and:

  <script type="text/javascript" src="blocks-os.js"></script>

to index.html.

Ellen

**Pull request closed without merging**
